name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: Build Release
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }

    steps:
      - name: Install pandoc
        shell: cmd
        run: choco install pandoc

      - name: Extract Version Number
        shell: bash
        run: echo "VERSION=${GITHUB_REF##*-}" >> $GITHUB_ENV

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.sys }}
          path-type: inherit
          install: >-
            autotools
            zip
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-SDL2
            mingw-w64-${{matrix.env}}-SDL2_mixer
            mingw-w64-${{matrix.env}}-SDL2_net
            mingw-w64-${{matrix.env}}-libpng
            mingw-w64-${{matrix.env}}-libsamplerate

      - uses: actions/checkout@v3

      - name: Configure
        run: |
          ./autogen.sh

      - name: Build
        run: make -j4

      - name: Package
        run: |
          cd pkg/win32
          make

      - name: Release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Crispy Doom ${{ env.VERSION }}
          bodyFile: CHANGELOG.md
          allowUpdates: true
          artifacts: pkg/win32/*.zip
